package empresa;
// Generated 30 dic. 2020 19:45:34 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private int id;
	private String dni;
	private String nombre;
	private String apellidos;
	private String telefono;
	private Set empleadoProyectos = new HashSet(0);
	private Set empleadoTareas = new HashSet(0);

	public Empleado() {
	}

	public Empleado(int id, String dni, String nombre, String apellidos, String telefono) {
		this.id = id;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
	}

	public Empleado(int id, String dni, String nombre, String apellidos, String telefono, Set empleadoProyectos,
			Set empleadoTareas) {
		this.id = id;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.empleadoProyectos = empleadoProyectos;
		this.empleadoTareas = empleadoTareas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getEmpleadoProyectos() {
		return this.empleadoProyectos;
	}

	public void setEmpleadoProyectos(Set empleadoProyectos) {
		this.empleadoProyectos = empleadoProyectos;
	}

	public Set getEmpleadoTareas() {
		return this.empleadoTareas;
	}

	public void setEmpleadoTareas(Set empleadoTareas) {
		this.empleadoTareas = empleadoTareas;
	}

}
