package orm;
// Generated 22-dic-2020 8:53:56 by Hibernate Tools 5.4.21.Final

/**
 * EmpleadoTareaId generated by hbm2java
 */
public class EmpleadoTareaId implements java.io.Serializable {

	private Integer idEmpleado;
	private int idTarea;

	public EmpleadoTareaId() {
	}

	public EmpleadoTareaId(int idTarea) {
		this.idTarea = idTarea;
	}

	public EmpleadoTareaId(Integer idEmpleado, int idTarea) {
		this.idEmpleado = idEmpleado;
		this.idTarea = idTarea;
	}

	public Integer getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(Integer idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public int getIdTarea() {
		return this.idTarea;
	}

	public void setIdTarea(int idTarea) {
		this.idTarea = idTarea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpleadoTareaId))
			return false;
		EmpleadoTareaId castOther = (EmpleadoTareaId) other;

		return ((this.getIdEmpleado() == castOther.getIdEmpleado()) || (this.getIdEmpleado() != null
				&& castOther.getIdEmpleado() != null && this.getIdEmpleado().equals(castOther.getIdEmpleado())))
				&& (this.getIdTarea() == castOther.getIdTarea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode());
		result = 37 * result + this.getIdTarea();
		return result;
	}

}
