package orm;
// Generated 22-dic-2020 8:53:56 by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos implements java.io.Serializable {

	private int id;
	private String nombre;
	private int duracion;
	private Date fechIn;
	private Date fechFin;
	private Set empleadoProyectos = new HashSet(0);
	private Set tareases = new HashSet(0);

	public Proyectos() {
	}

	public Proyectos(int id, String nombre, int duracion, Date fechIn) {
		this.id = id;
		this.nombre = nombre;
		this.duracion = duracion;
		this.fechIn = fechIn;
	}

	public Proyectos(int id, String nombre, int duracion, Date fechIn, Date fechFin, Set empleadoProyectos,
			Set tareases) {
		this.id = id;
		this.nombre = nombre;
		this.duracion = duracion;
		this.fechIn = fechIn;
		this.fechFin = fechFin;
		this.empleadoProyectos = empleadoProyectos;
		this.tareases = tareases;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	public Date getFechIn() {
		return this.fechIn;
	}

	public void setFechIn(Date fechIn) {
		this.fechIn = fechIn;
	}

	public Date getFechFin() {
		return this.fechFin;
	}

	public void setFechFin(Date fechFin) {
		this.fechFin = fechFin;
	}

	public Set getEmpleadoProyectos() {
		return this.empleadoProyectos;
	}

	public void setEmpleadoProyectos(Set empleadoProyectos) {
		this.empleadoProyectos = empleadoProyectos;
	}

	public Set getTareases() {
		return this.tareases;
	}

	public void setTareases(Set tareases) {
		this.tareases = tareases;
	}

}
