package orm;
// Generated 22-dic-2020 9:10:51 by Hibernate Tools 5.4.21.Final

/**
 * EmpleadoTarea generated by hbm2java
 */
public class EmpleadoTarea implements java.io.Serializable {

	private EmpleadoTareaId id;
	private Empleados empleados;
	private Tareas tareas;

	public EmpleadoTarea() {
	}

	public EmpleadoTarea(EmpleadoTareaId id, Tareas tareas) {
		this.id = id;
		this.tareas = tareas;
	}

	public EmpleadoTarea(EmpleadoTareaId id, Empleados empleados, Tareas tareas) {
		this.id = id;
		this.empleados = empleados;
		this.tareas = tareas;
	}

	public EmpleadoTareaId getId() {
		return this.id;
	}

	public void setId(EmpleadoTareaId id) {
		this.id = id;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public Tareas getTareas() {
		return this.tareas;
	}

	public void setTareas(Tareas tareas) {
		this.tareas = tareas;
	}

}
