package orm;
// Generated 22-dic-2020 9:10:51 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tareas generated by hbm2java
 */
public class Tareas implements java.io.Serializable {

	private int id;
	private Proyectos proyectos;
	private String nombre;
	private String estado;
	private int horas;
	private Set empleadoTareas = new HashSet(0);

	public Tareas() {
	}

	public Tareas(int id, Proyectos proyectos, String nombre, int horas) {
		this.id = id;
		this.proyectos = proyectos;
		this.nombre = nombre;
		this.horas = horas;
	}

	public Tareas(int id, Proyectos proyectos, String nombre, String estado, int horas, Set empleadoTareas) {
		this.id = id;
		this.proyectos = proyectos;
		this.nombre = nombre;
		this.estado = estado;
		this.horas = horas;
		this.empleadoTareas = empleadoTareas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Proyectos getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Proyectos proyectos) {
		this.proyectos = proyectos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	public Set getEmpleadoTareas() {
		return this.empleadoTareas;
	}

	public void setEmpleadoTareas(Set empleadoTareas) {
		this.empleadoTareas = empleadoTareas;
	}

}
