package empresa;
// Generated 29 dic. 2020 18:49:55 by Hibernate Tools 5.4.21.Final

/**
 * EmpleadoProyecto generated by hbm2java
 */
public class EmpleadoProyecto implements java.io.Serializable {

	private EmpleadoProyectoId id;
	private Empleado empleado;
	private Proyecto proyecto;

	public EmpleadoProyecto() {
	}

	public EmpleadoProyecto(EmpleadoProyectoId id, Empleado empleado, Proyecto proyecto) {
		this.id = id;
		this.empleado = empleado;
		this.proyecto = proyecto;
	}

	public EmpleadoProyectoId getId() {
		return this.id;
	}

	public void setId(EmpleadoProyectoId id) {
		this.id = id;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

}
