package empresa;
// Generated 29 dic. 2020 18:49:55 by Hibernate Tools 5.4.21.Final

/**
 * EmpleadoTarea generated by hbm2java
 */
public class EmpleadoTarea implements java.io.Serializable {

	private EmpleadoTareaId id;
	private Empleado empleado;
	private Tarea tarea;

	public EmpleadoTarea() {
	}

	public EmpleadoTarea(EmpleadoTareaId id, Tarea tarea) {
		this.id = id;
		this.tarea = tarea;
	}

	public EmpleadoTarea(EmpleadoTareaId id, Empleado empleado, Tarea tarea) {
		this.id = id;
		this.empleado = empleado;
		this.tarea = tarea;
	}

	public EmpleadoTareaId getId() {
		return this.id;
	}

	public void setId(EmpleadoTareaId id) {
		this.id = id;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Tarea getTarea() {
		return this.tarea;
	}

	public void setTarea(Tarea tarea) {
		this.tarea = tarea;
	}

}
